export const TYPES = {
  BrowserContext: Symbol.for('BrowserContext'),
  BrowserStorageStateService: Symbol.for('BrowserStorageStateService'),
  Domain: Symbol.for('Domain'),
  DownloadService: Symbol.for('DownloadService'),
  DownloadToServerStrategy: Symbol.for('DownloadToServerStrategy'),
  DownloadUri: Symbol.for('DownloadUri'),
  ImageScraper: Symbol.for('ImageScraper'),
  Name: Symbol.for('Name'),
  NatsConnection: Symbol.for('NatsConnection'),
  Password: Symbol.for('Password'),
  PixivImageRequestListener: Symbol.for('PixivImageRequestListener'),
  PixivPostRequestListener: Symbol.for('PixivPostRequestListener'),
  PixivScraper: Symbol.for('PixivScraper'),
  Username: Symbol.for('Username'),
};
